### ISSUE TITLE
NSBencodeSerialization @ 3612a7a

### ISSUE THREAD

**Issue by urosch** [Qata/BarMagnet#20]
NSBencodeSerialization @ 3612a7a
gives 404 error - not found

**Comment by NeskireDK** [comment]
Yeah i too can't compile. 
After successfully: git clone https://github.com/Qata/BarMagnet/issues/20
running the command: git submodule update --init --recursive
Yields
`fatal: reference is not a tree: 3612a7a88f020f23c33ca69b544182039f422d2a
Unable to checkout '3612a7a88f020f23c33ca69b544182039f422d2a' in submodule path 'NSBencodeSerialization'`

**Comment by NeskireDK** [comment]
I fixed it by manually downloading: github.com/Qata/NSBencodeSerialization
and its dependency: https://github.com/Marxon13/M13OrderedDictionary

After that it was a simple task of using the correct OrderedDictionary, since it was renamed to M13. There are 4 references throughout the project, should be simple enough to find them with the error list :)

**Comment by Dasoren** [comment]
Also ran into this issue, going to try @NeskireDK fix, but so far it has been failing on me.

**Comment by Dasoren** [comment]
I was able to get the NSB and M13 repos downloaded and working, but alas I have other errors now, #23
