### ISSUE TITLE
Right click in Open UI

### ISSUE THREAD

**Issue by phunkyfish** [Qata/BarMagnet#32]
As this is an iOS app I was wondering if there is a method of accessing the context menus in the various Web UIs?

I'd like to be able to set labels from within the Open UI Screen but can't unless I can do some orm of right click.

**Comment by galori** [comment]
This is up to the torrent client themselves - BarMagnet merely links to them. If you click on the "SHARE" link at the bottom and then choose "SAFARI" you'll see the same Web UI opened directly in Safari (which you can also do directly without ever using the app).

Try a long press, sometimes you can get the same context menu by using a long press instead of a right click.
